
export const REDUX_LISTTREE_EDIT_LIST_REQ   = 'REDUX_LISTTREE_EDIT_LIST_REQ';
export const REDUX_LISTTREE_EDIT_LIST_DONE  = 'REDUX_LISTTREE_EDIT_LIST_DONE';
export const REDUX_LISTTREE_EDIT_LIST_ERR   = 'REDUX_LISTTREE_EDIT_LIST_ERR';